import Head from 'next/head';
import { readJSONData } from '@/utils/json.utils';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home({ post }) {
    const router = useRouter();

    useEffect(() => {
        router.push('/mail/inbox');
    }, []);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main></main>
        </>
    );
}

export async function getStaticProps() {
    // Call an external API endpoint to get posts.
    // You can use any data fetching library
    const res = await readJSONData('json/inbox.json');

    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
        props: {
            post: res,
        },
    };
}
